# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('username', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('lID', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('watt', models.FloatField()),
                ('pID', models.IntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=64)),
                ('state', models.BooleanField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
