# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmableSwitch', '0002_auto_20160221_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='stateChanged',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='points',
            name='whoChanged',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
