# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmableSwitch', '0003_auto_20160222_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='stateChanged',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
