# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmableSwitch', '0005_auto_20160222_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='whoChanged',
            field=models.CharField(max_length=32),
        ),
    ]
